### ISSUE TITLE
event handler error

### ISSUE THREAD

**Issue by phucho0237** [Miro-Network/Miro-Lofi#1]
![Screenshot from 2023-01-15 10-51-46](https://user-images.githubusercontent.com/88989555/212522071-40f9c2fb-4510-4425-9b8c-a74efee397e1.png)

**Comment by Elham-EN** [comment]
Hi @phucho0237. Can you elaborate more on the issue, so that I can a better idea of the problem.

**Comment by phucho0237** [comment]
> Hi @phucho0237. Can you elaborate more on the issue, so that I can a better idea of the problem. 

It's like the picture, printed the ascii table but the event is not working

**Comment by Elham-EN** [comment]
Can you assign me?

**Comment by Elham-EN** [comment]
I solved the problem.

**Comment by phucho0237** [comment]
@Elham-EN done

**Comment by phucho0237** [comment]
i created a new branch

**Comment by phucho0237** [comment]
still not work :(

**Comment by phucho0237** [comment]
![Screenshot from 2023-01-15 16-24-00](https://user-images.githubusercontent.com/88989555/212533102-42df2ca6-769c-4d2a-abbd-dc09b4995bfc.png)

**Comment by phucho0237** [comment]
> ![Screenshot from 2023-01-15 16-24-00](https://user-images.githubusercontent.com/88989555/212533102-42df2ca6-769c-4d2a-abbd-dc09b4995bfc.png)

if it work, it will execute this command in src/events/client/ready.js

![Screenshot from 2023-01-15 16-26-05](https://user-images.githubusercontent.com/88989555/212533176-7d386f2b-b6b6-4f99-b023-30880fb6443e.png)

**Comment by Elham-EN** [comment]
Okay now it displays Online as XXXXX#12133 based on the ready event. Please review the code.
